### ISSUE TITLE
Find an appropriate evaluation metric to quantify the accuracy of our model

### ISSUE THREAD

**Issue by meghana-holla** [ManishShettyM/ResumeRise#3]

**Comment by manishshettym** [comment]
Solution as of now : Classify/Rank the test set using intuitive approach and compare the results.
But the specific metric to be used needs to be clear.

**Comment by manishshettym** [comment]
Accuracy and confusion matrix provide a good metric now that the model is clearer.
It also allows various models to be compared too.
