### ISSUE TITLE
NER ?

### ISSUE THREAD

**Issue by manishshettym** [ManishShettyM/ResumeRise#4]
Spacy as we saw uses Named Entity Recognition model ..

Then later move onto maybe using some other model and compare results ??

**Comment by meghana-holla** [comment]
We've compared spaCy to its alternatives, and come to a conclusion that spaCy is the faster and the more efficient compared to the rest . Hence, STICKING TO SPACY!

**Comment by manishshettym** [comment]
Spacy was tried for phase1 of the project and seems to be very statically designed to json formatted documents which have previously been annotated. 
This was making it difficult for any kind of flexibility in using a clear resume dataset and also evaluating whether or not the model is doing anything at all was confusing.

Thus closing this issue with an inference that the classification can be done better of with simpler models and some rigorous pre processing techniques.
