### ISSUE TITLE
Supervised or Unsupervised method for document classification? 

### ISSUE THREAD

**Issue by meghana-holla** [ManishShettyM/ResumeRise#5]
Study and experiment a little and get an idea of what to use for classification task. (Keep adding links to articles/papers if found helpful)

**Comment by manishshettym** [comment]
Clustering method tried for Resume Similarity:
https://github.com/ManishShettyM/ResumeRise/blob/master/Utils/Resume%20Similarity.ipynb

Very sparse and probably needs some kind of SVD to reduce parameters.
So sticking with the supervised models.
